# Unit 02: Computing with Data in Python

# Outline of ECE 3

The course ECE 3 is organized into 4 units.

- Unit 01: Welcome to Python
- **Unit 02: Computing with Data in Python**
- Unit 03: Summarizing Data in Python
- Unit 04: Predicting from Data with Machine Learning in Python

# Outline of Unit 02

- **02: Computing with Data in Python**
  - Vector
      - **Vectors: assigning, accessing, visualizing**
      - **Vector addition, subtraction, scaling, linear combination**
      - Inner products, affine function, norm, distance, angle
  - Matrix
      - Matrices, special matrices
      - Matrix transpose, addition, subtraction, scaling
      - Matrix-vector multiplication, Matrix-matrix multiplication

# Outline of Unit 02

- **02: Computing with Data in Python**
  - Vector
      - Vectors: assigning, accessing, visualizing
      - Vector addition, subtraction, scaling, linear combination
      - **Inner products, affine function, norm, distance, angle**
  - Matrix
      - **Matrices, special matrices**
      - Matrix transpose, addition, subtraction, scaling
      - Matrix-vector multiplication, Matrix-matrix multiplication

## Inner Product

$\color{#EF5645}{\text{Definition}}$: The inner product (or dot product) of n-vectors a and b is the scalar:
$$a^T b = a_1b_1 + a_2b_2 + · · · + a_nb_n.$$
- Other notations: $〈a, b〉, 〈a|b〉, (a, b), a · b.$
- $\color{#003660}{\text{In Python}}$, we use `inner` or `dot` (from `numpy`).

$\color{#047C91}{\text{Exercise}}$: Compute the inner product of $a = (1, 0, 2)$ and $b = (-1, 1, 2)$.

In [7]:
import numpy as np

"""Compute the inner product of two vectors."""
a = np.array([1,0,2])
b = np.array([-1,1,2])

# print(np.sum(a * b))
# print(np.inner(a, b))
# print(np.dot(a,b))
# print(1*(-1) + 0*1 + 2*2)

### Properties of inner product

$\color{#6D7D33}{\text{Properties}}$: For $n$-vectors $a, b, c$ and scalars $\gamma$:
1. Commutativity: $a^T b = b^T a$
2. Homogeneity: $(γa)^T b = γ(a^T b)$
3. Distributivity: $(a + b)^T c = a^T c + b^T c$

$\color{#047C91}{\text{Exercise}}$: Write a function that computes the output of the following polynomial using the inner product function:

$$f(x) = - x^4 + 5x^3 + 2x^2 + 7$$

Let $a$  be the $5$-vector of coefficients $a=(7, 0, 2, 5, -1)$ and $b$  be the $5$-vector of monomials $b=(x^0, x^1, x^2, x^3, x^4)$

Then $f(x) = a \cdot b$. 

We can evaluate $f(x)$ at $x=2$:

$$f(2) = -(2)^4 + 5(2)^3 + 2(2)^2 + 7 = -16 + 40 + 8 + 7 = 39$$

$$f(x) = - x^4 + 5x^3 + 2x^2 + 7$$

In [10]:
def f(x):    
    coef = np.array([7, 0, 2, 5, -1])
    x_powers = np.array([x**0, x**1, x**2, x**3, x**4])
    output = np.dot(coef,x_powers)
    return output

#print(f(2))

## Norm

$\color{#EF5645}{\text{Definition}}$: The *Euclidean norm*, or just *norm*, of an $n$-vector $x$ is:
$$||x|| = \sqrt{x_1^2 + ... + x_n^2}.$$ 

<!-- = \sqrt{x^Tx} -->

$\color{#EF5645}{\text{Remark}}$: The norm is equal to the absolute value for $n=1$.

$\color{#EF5645}{\text{Question}}$: There is a famous theorem about the Euclidean norm for $n=2$. What is it?

 -> Pythagorean theorem!

$\color{#003660}{\text{In Python}}$, the module `linalg` from the package `numpy` has a function called `norm`.

In [11]:
x = np.array([2, -1, 2])

print(np.linalg.norm(x))

3.0


$\color{#047C91}{\text{Exercise}}$: Can you write a function that computes the norm using the vector operators we have already seen?

In [13]:
def norm(a):
    return np.sqrt(np.dot(a,a))

x = np.array([2, -1, 2])

# print(norm(x))
# print(np.linalg.norm(x))

### Properties of the Norm

$\color{#6D7D33}{\text{Properties}}$: For any scalar $\beta$ and any $n$-vectors $x, y$:
1. Homogeneity: $||\beta x|| = |\beta|||x||$
2. Triangle inequality: $||x+y|| \leq ||x|| + ||y||$
3. Nonnegative: $||x|| \geq 0$
4. Definite: $||x|| = 0$ if and only if $x = 0$

### Triangle Inequality

$\color{#6D7D33}{\text{Theorem}}$: For any two $n$-vectors $x$ and $y$, we have the triangle inequality:
$$\|x + y\| \leq \|x\| + \|y\|.$$

$\color{#047C91}{\text{Exercise}}$: Can you prove this inequality using geometrically? 

*hint:* Think about this in 2D.

Notice that given two n-vectors $x$ and $y$ we can make a 2D triangle by connecting these points with the origin and themselves.

<center><img src="figs/01_triangle_inequality.png" alt="Drawing" width=350px/></center>

## Distance

$\color{#EF5645}{\text{Definition}}$: The *Euclidean distance*, or just *distance*, between $n$-vectors $a$ and $b$ is:
$$dist(a, b) = ||a - b||.$$

$\color{#EF5645}{\text{Remark}}$: This definition agrees with ordinary distance for $n = 1, 2, 3.$

## Angle

$\color{#EF5645}{\text{Definition}}$: The _angle_ between two non-zeros $n$-vectors $a$ and $b$ is:
$$\angle(a, b) = arccos\left( \frac{a^Tb}{||a||||b||} \right).$$

$\color{#EF5645}{\text{Remark}}$: It coincides with the ordinary angle in 2D and 3D.

$$\angle(a, b) = arccos\left( \frac{a^Tb}{||a||||b||} \right).$$

In [16]:
import numpy as np
def angle(a, b):
    product = np.linalg.norm(a)* np.linalg.norm(b)
    fraction = np.inner(a, b) / (product)
    return np.arccos(fraction)

In [ ]:
a = [1, -1]
b = [0.1, 1]

print(angle(a, b))
print(np.pi / 2)

Write: $\theta = \angle(a, b)$ 
- $θ = π/2 = 90^\circ$: a, b are *orthogonal*: $a ⊥ b$ ($a^T b = 0$) 
- $θ = 0$: a, b are _aligned_ ($a^T b = ‖a‖ ‖b‖$) 
- $θ = π = 180^\circ$: a, b are _anti-aligned_ ($a^T b = −‖a‖ ‖b‖$)
- $θ ≤ π/2 = 90^\circ$: a, b make an _acute angle_ ($a^T b ≥ 0$)
- $θ ≥ π/2 = 90^\circ$: a, b make an _obtuse angle_ ($a^T b ≤ 0$)

<center><img src="figs/03_angles.jpg" alt="default"/></center>

### Cauchy-Schwarz Inequality

$\color{#6D7D33}{\text{Theorem}}$: For any two $n$-vectors $a$ and $b$, we have the Cauchy-Schwarz inequality:
$$|a^Tb| \leq ||a||||b||.$$

$\color{#047C91}{\text{Exercise}}$: Can you use this inequality to prove the triangle inequality?

## Some Terminology of Vectors


### Unit Vector or Normalized Vector

$\color{#EF5645}{\text{Definition}}$: An $n$-vector $a$ is a *unit vector* or *normalized* if and only if,
$$\|a\| = 1$$

### Orthogonal

$\color{#EF5645}{\text{Definition}}$: If the _angle_ between two non-zeros $n$-vectors $a$ and $b$ is $\frac{\pi}{2}$, then we call these vectors *orthogonal*.  This is true if and only if,
$$a^\intercal b = a \centerdot b = 0.$$

### Orthonormal

$\color{#EF5645}{\text{Definition}}$: Two $n$-vectors $a$ and $b$ are *orthonormal* if and only if they are orthogonal unit vectors,
$$\|a\| = \|b\| = 1 \qquad\text{and}\qquad a \centerdot b = 0.$$

$\color{#047C91}{\text{Exercise}}$: Which of the following pairs of vectors are orthonormal?

- $a = [1,1,1,0]$ and $b = [0,1,1,1]$
- $a = [1,1,0,0]$ and $b = [0,0,1,1]$
- $a = [1,0,0,0]$ and $b = [0,0,0,1]$

In [17]:
a = np.array([1,0,0,0])
b = np.array([0,0,0,1])

# Check that a and b are unit vectors
print(np.linalg.norm(a) == 1)
print(np.linalg.norm(b) == 1)

# Check that a and b are orthgonal
print(np.dot(a,b) == 0)

True
True
True


# 1. What is a Matrix

<center><img src="figs/06_matrix_everywhere.gif" alt="default", width=1000px/></center>

## Definition of a Matrix

$\color{#EF5645}{\text{Definition}}$: A _matrix_ is a rectangular array of numbers, e.g.:
$$A =\begin{vmatrix}
0   & 1  & -2.3  \\
1.3 & 4  & -0.1 
\end{vmatrix}$$

- Its _size_ or _shape_ is: (number of rows) x (number of columns).
- Its elements are called: _entries, coefficients_.
- $A_{i, j}$ refers to element at ith row and jth column.
  - i is the _row index_ and j is the _column index_.
  
$\color{#EF5645}{\text{Remark:}}$ We often denote a matrix with a capital letter such as A and vectors with a lower case letter such as a.

### Examples in ECE and beyond


- Weather: $A_{ij}$ is rainfall data at location $i$ on day $j$.
- Finances: $A_{ij}$ is the return of asset $i$ in period $j$.
- Images: $A_{ij}$ is intensity value at $i, j$.

$\color{#003660}{\text{In Python}}$, we use `numpy` and `np.array` to build matrices. We compute its shape with `shape`.

In [128]:
import numpy as np


A = np.array([
    [0, 1, -2.3], 
    [1.3, 4, -0.1]
])
print(A)
print(np.shape(A))
print(A.size)

[[ 0.   1.  -2.3]
 [ 1.3  4.  -0.1]]
(2, 3)
6


$\color{#003660}{\text{In Python}}$, we can access the elements of the matrix.

In [129]:
A = np.array([
    [0, 1, -2.3], 
    [1.3, 4, -0.1]
])

print(A[0, 0])
print(A[0, 2])

0.0
-2.3


## Sizes/Shapes of Matrices

$\color{#EF5645}{\text{Definitions}}$: A $n \times m$ matrix $A$ is:
- _tall_ if n > m (more rows than columns)
- _wide_ if n < m (more columns than rows)
- _square_ if n = m (same columns as rows)

$\color{#EF5645}{\text{Special cases}}$:
- A 1 x 1 matrix is a number or scalar.
- A n x 1 matrix is an $n$-vector.
- A 1 x m matrix is a $m$-row-vector. 

Starting now, we will distinguish vectors and row vectors.

## Column representation of a matrix

An $n \times m$ matrix $A$ can be repersented an ordered collection of m n-vectors $a_1, ..., a_n$:
  $$A = [a_1 ... a_n]$$
The jth column of $A$ is the $n$-vector:
$$a_j = \begin{vmatrix}
A_{1j} \\
\vdots \\
A_{nj}
\end{vmatrix}$$

## Row representation of a matrix
An $n \times m$ matrix $A$ can be repersented an ordered collection of n m-row-vectors $b_1, ..., b_n$:
  $$A = \begin{vmatrix}
  b_1 \\
  \vdots \\
  b_m
  \end{vmatrix}$$
The ith row is the $m$-row-vector: 
$$[A_{i1}, ..., A_{im}]$$

## Slices of a matrix

$\color{#EF5645}{\text{Definition}}$ The slice of matrix $A_{p:q, r:s}$ is the matrix:
$$\begin{vmatrix}
A_{pr} & A_{p, r+1} & ... & A_{ps}  \\
... & ... & ... & ... \\
A_{qr} & A_{q, r+1} & ... & A_{qs}
\end{vmatrix}.$$

$\color{#003660}{\text{In Python}}$, we can extract rows, columns and slices:

In [130]:
A = np.array([
    [1.1, 2.2, 3.3], 
    [4.4, 5.5, 6.6], 
    [7.7, 8.8, 9.9]]) 
print("Matrix:")
print(A)

print("Columns:")
print(A[:,0]); print(A[:,1]); print(A[:,2])

print("Rows:")
print(A[0, :]); print(A[1,:]); print(A[2,:])

print("Matrix Slice:")
A[0:2, 1:3]

Matrix:
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
Columns:
[1.1 4.4 7.7]
[2.2 5.5 8.8]
[3.3 6.6 9.9]
Rows:
[1.1 2.2 3.3]
[4.4 5.5 6.6]
[7.7 8.8 9.9]
Matrix Slice:


array([[2.2, 3.3],
       [5.5, 6.6]])

## Special Matrices

### Zero Matrix

$\color{#EF5645}{\text{Definition}}$: The $n \times m$ matrix with all entries 0 is denoted $0_{n \times m}$ or just $0$ and is called a _zero matrix_. 

### Ones Matrix

$\color{#EF5645}{\text{Definition}}$: $n \times m$ matrix with all entries 1 is denoted $1_{n \times m}$ or just $1$ and is called a _ones matrix_.

### Identity Matrix

$\color{#EF5645}{\text{Definition}}$: The $n \times n$ matrix with all entries 0 except the diagonal elements are 1 is denoted $I_n$ or just $I$ is the _identity matrix_.

$\color{#003660}{\text{In Python}}$, we use `zeros` , `ones`, and `identity` or `eye` (from `numpy`) to build these vectors.

In [133]:
n, m = 3, 4

zero = np.zeros((n,m))
print(zero)

ones = np.ones((n,m))
print(ones)

I = np.eye(n)
I = np.identity(n)
print(I)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


$\color{#047C91}{\text{Exercise}}$: How many elements of an $n$ identity matrix are zero?

In [135]:
n = 1200
I = np.eye(n)
num_zero = np.sum(I == 0)

print(num_zero)
print(n * (n - 1))

1438800
1438800


# Recap of Unit 02

- **02: Computing with Data in Python**
  - Vector
      - Vectors: assigning, accessing, visualizing
      - Vector addition, subtraction, scaling, linear combination
      - **Inner products, affine function, norm, distance, angle**
  - Matrix
      - **Matrices, special matrices**
      - Matrix transpose, addition, subtraction, scaling
      - Matrix-vector multiplication, Matrix-matrix multiplication

# Next week with Louisa!

The course ECE 3 is organized into 4 units.

- Unit 01: Welcome to Python
- Unit 02: Computing with Data in Python
- **Unit 03: Summarizing Data in Python**
- Unit 04: Predicting from Data with Machine Learning in Python