# 09 Matrix Multiplication

<center><img src="figs/09_six_degrees.png" alt="default" width=600px/></center>

<center>Six degrees of separation theory</center>

#### Unit 1: Vectors, Textbook Ch. 1-5

#### Unit 2: Matrices, Textbook Ch. 6-11
- 06 Matrices
- 07 Linear Equations
- 08 Linear Dynamical Systems
- **_09 Matrix Multiplication_**
- 10 Matrix Inverse

#### Unit 3: Least Squares, Textbook Ch. 12-14

##### Outline: 09 Matrix Multiplication

- **[Matrix Multiplication](#sec-matrices)**
- [Composition of linear functions](#sec-matrices)
- [Matrix powers](#sec-matrices)
- [QR factorization](#sec-matrices)

### Matrix Multiplication

$\color{#EF5645}{\text{Definition}}$: Consider $m \times p$ matrix $A$ and $p \times n$ matrix $B$. The _matrix multiplication_, written $C = AB$ is defined as:
$$C_{ij} = \sum_{k=1}^p  A_{ik}B_{kj} \text{ for } i= 1, ...m , j = 1, ...n$$

$\color{#047C91}{\text{Exercise}}$: Compute the matrix multiplication for the following matrices.

<center><img src="figs/09_mat_ab.png" width=400px alt="default"/></center>

### Special Cases of Matrix Multiplication

$\color{#EF5645}{\text{Remark}}$: For $x, y$ vectors, and $A$ a matrix, the following are special cases of matrix multiplication:
- inner-product $x^T y$,
- matrix vector multiplication $Ax$.


$\color{#EF5645}{\text{Definition}}$: The _outer product_ of $m$-vector $x$ and $n$-vector $y$ is defined as $xy^T$. It is also a special case of matrix multiplication.

$\color{#6D7D33}{\text{Properties}}$: For matrices $A, B, C$ and identity matrix $I$, we have the properties:
- Associativity: $$(AB)C = A(BC)$$
- Distributivity: $$A(B+C)  = AB + AC$$
- Transpose: $$(AB)^T = B^T A^T$$
- $AI = A$ and $IA = A$.

$\color{#047C91}{\text{Exercise}}$: Compute $B^TA^T$ for the following matrices.
<center><img src="figs/09_mat_ab.png" width=500px alt="default"/></center>

$\color{#EF5645}{\text{Important remark}}$: $AB = BA$ does NOT hold in general. We say that the matrix multiplication is NOT commutative.

$\color{#047C91}{\text{Exercise}}$: Compute $BA$ for the following matrices. Observe that it differs from $AB$.

<center><img src="figs/09_mat_ab.png" width=400px alt="default"/></center>


### Exercises

$\color{#047C91}{\text{Exercise}}$: Let $A$ be a matrix and $I$ be the identity matrix. Show that $AI = A$.

$\color{#047C91}{\text{Exercise}}$: Given $m$-vector $x$ and $n$-vector $y$, write the outer product $xy^T$ using the entries of $x$ and $y$.

$\color{#003660}{\text{In Python}}$, we us `np.matmul` or `@` to compute the matrix multiplication. Verify that the matrix multiplication is generally NOT commutative by choosing matrices $A, B$ and computing $AB$ and $BA$.

In [8]:
import numpy as np
A = np.array([[1., 3.],[3., 5.]])
B = np.array([[-1., 3.3],[3.6, 5.6]])
C = A @ B; print(C) #np.matmul(A, B)
B @ A

[[ 9.8 20.1]
 [15.  37.9]]


array([[ 8.9, 13.5],
       [20.4, 38.8]])

### Inner-product interpretation

$\color{#6D7D33}{\text{Properties}}$: Consider matrices $A, B$ with $a_i^T$ the rows of $A$ nd $b_j$ the columns of $B$. We have: 

<center><img src="figs/09_ab_innerprod.png" width=500px alt="default"/></center>


The matrix multiplication gathers the inner-products of rows of $A$ and columns of $B$.

### Building Matrices from Matrices

$\color{#EF5645}{\text{Definition}}$: Let $A$ be an $m \times n$ matrix with columns $a_1, .., a_n$. The Gram matrix $G$ of $A$ is:
<center><img src="figs/09_gram.png" width=600px alt="default"/></center>
 The Gram matrix gives all inner products of columns of $A$.

$\color{#6D7D33}{\text{Property}}$: If $G = I$ then columns of $A$ are orthonormal.

##### Outline: 09 Matrix Multiplication

- [Matrix Multiplication](#sec-matrices)
- **[Composition of linear functions](#sec-matrices)**
- [Matrix powers](#sec-matrices)
- [QR factorization](#sec-matrices)

### Composition of Functions

$\color{#EF5645}{\text{Definition}}$: Consider $f: \mathbb{R}^p \rightarrow \mathbb{R}^m$ and $g: \mathbb{R}^n \rightarrow \mathbb{R}^p$. 

The function $h: \mathbb{R}^n \rightarrow \mathbb{R}^m$ defined as: $h(x) = f(g(x))$ for all $x \in \mathbb{R}^n$ is called the composition of $f$ and $g$.


### Composition of Linear Functions


$\color{#6D7D33}{\text{Proposition}}$: Assume functions $f, g$ are linear functions, thus can be written as: $f(u) = Au$ and $g(x)=Bx$ for $n$-vector $x$ and $p$-vector $u$. Then the composition $h$ can be written as: $h(x) = (AB)x$.



$\color{#EF5645}{\text{Remark}}$: This means that:
- the composition of linear functions is a linear function,
- the associated matrix is product of matrices of the functions.

##### Outline: 09 Matrix Multiplication

- [Matrix Multiplication](#sec-matrices)
- [Composition of linear functions](#sec-matrices)
- **[Matrix powers](#sec-matrices)**
- [QR factorization](#sec-matrices)

### Matrix Square

$\color{#EF5645}{\text{Definition}}$: The square of a square matrix $A$, written $A^2$, is defined as: $A^2 = AA$.

$\color{#EF5645}{\text{Remark}}$:  $A^2$ is NOT computed by squaring each entry of matrix $A$. 

### Matrix Power

$\color{#EF5645}{\text{Definition}}$: For a positive integer $k$, the $k$th power of a matrix $A$, written $A^k$ is defined as: $A^k = A...A$ with $k$ matrices $A$ multiplied. By convention, $A^0 = I$ the identity matrix.


$\color{#EF5645}{\text{Remark}}$: $A^k$ is NOT computed by taking the power $k$ of each entry of matrix $A$. 

$\color{#EF5645}{\text{Remarks}}$: $\color{#003660}{\text{In Python}}$:
-  `A ** 2` computes the square of each entry, and not does compute $A^2$.
-  `A @ A` or `np.linalg.matrix_power` can compute $A^2$.

In [11]:
A = np.array([[5., 7., 6.],[2., 4., -2.],[2., 3., 4.]])
print(A**2)
print(np.linalg.matrix_power(A, 10))

[[25. 49. 36.]
 [ 4. 16.  4.]
 [ 4.  9. 16.]]
[[3.03672874e+09 4.92159758e+09 1.58516828e+09]
 [5.88044466e+08 9.53055282e+08 3.06781144e+08]
 [1.48287008e+09 2.40327024e+09 7.74090160e+08]]


$\color{#047C91}{\text{Exercise}}$: Take the adjacency matrix associated with the graph below. We state that $(A^l)_{ij}$ is equal to number of paths of length $l$ going from $j$ to $i$.

<center><img src="figs/09_adjacency.png" alt="default", width=650px/></center>


Verify this statement in a special case, by computing $(A^2)_{11}$.

### Inverse

$\color{#EF5645}{\text{Definition}}$: If ...

We say that $A$ is invertible. 

We denote $A^{-1}$ the (unique) inverse of $A$.



$\color{#6D7D33}{\text{Properties}}$:
- If $A$ is invertible then $A$ is square.
- The inverse of the inverse is: $(A^{-1})^{-1} = A$.

$\color{#047C91}{\text{Exercise}}$: Prove the above statements.

### Which Matrices are Invertible?

$\color{#6D7D33}{\text{Properties}}$: These matrices are always invertible:
- Any lower triangular matrix $L$ with nonzero diagonal entries is invertible. 
- Any upper triangular $R$ with nonzero diagonal entries is invertible.

$\color{#047C91}{\text{Exercise}}$: Give examples of invertible matrices.

### Computing Inverses: $2 \times 2$ matrices

$\color{#6D7D33}{\text{Properties}}$: Consider $A$ is a $2 \times 2$ matrix:
- $A$ is invertible if and only if $A_{11}A_{22} \neq A_{12}A_{21}$.
- In this case:

<center><img src="figs/lec10_2by2_inverse.png" width=400px alt="default"/></center>


$\color{#047C91}{\text{Exercise}}$: Compute the inverse of:

<center><img src="figs/lec10_exercise_2by2_inverse.png" width=100px alt="default"/></center>


###  Computing Inverses

$\color{#6D7D33}{\text{Properties}}$: Some matrices have "easy" inverses:
- The identity matrix: 
  - Then $I^{-1} = I$
- A square $Q$ matrix that verifies $Q^TQ = I$:
  - Then $Q^{-1} = Q^T$.
- A diagonal matrix $D = diag(a_1, ..., a_n)$ with nonzero elements:
  - Then $D^{-1} = diag(\frac{1}{a_1}, ..., \frac{1}{a_n}).$

### Computing Inverses

$\color{#6D7D33}{\text{Properties}}$: Consider invertible square matrices $A, B$ with known inverses $A^{-1}, B^{-1}$.
- $(AB)^{-1} = B^{-1}A^{-1}$
- $(A^T)^{-1} = (A^{-1})^T$

$\color{#047C91}{\text{Exercise}}$: Prove the two first bullet points.


$\color{#EF5645}{\text{Notation}}$: Negative powers! $A^{-k} = (A^{k})^{-1}$

### Computing Inverses in Python

$\color{#003660}{\text{In Python}}$, we use `np.linalg.inv` to compute the inverse.

In [7]:
import numpy as np

A = np.array([
    [1, 2],
    [0, 4]
])
print(np.linalg.inv(A))

[[ 1.   -0.5 ]
 [ 0.    0.25]]


$\color{#047C91}{\text{Exercise}}$: Give an idea on how to prove the six degrees separation theory.

<center><img src="figs/09_six_degrees.png" alt="default" width=350px/></center>

This is the theory that any person on the planet can be connected to any other person on the planet through a chain of acquaintances that has no more than five intermediaries.

# TODO: PCA