# 06 Matrices

<center><img src="figs/06_matrix_everywhere.gif" alt="default"/></center>

# Class Survey

Fill out the survey at this link! :) 

https://forms.gle/E7sQc2URLSvkJcqu7

#### Unit 1: Vectors, Book ILA Ch. 1-5

#### Unit 2: Matrices, Book ILA Ch. 6-11 + Book IMC Ch. 2
- **_06 Matrices_**
- 07 Linear Equations
- 08 Linear Dynamical Systems
- 09 Matrix Multiplication
- 10 Matrix Inverse

#### Unit 3: Least Squares, Book ILA Ch. 12-14 + Book IMC Ch. 8
#### Unit 4: Eigen-decomposition, Book IMC Ch. 10, 12, 19

# Outline: 06 Matrices

- **[Matrices](#sec-matrices)**
- [Matrix-vector multiplication](#matvec)
- [Examples](#examples)

# Matrices

$\color{#EF5645}{\text{Definition}}$: A matrix is a rectangular array of numbers, e.g.:
$$A = \begin{bmatrix}
0   & 1  & -2.3  \\
1.3 & 4  & -0.1 
\end{bmatrix}$$

- Its size, or shape, is: (row dimension) x (column dimension).
  - $\color{#047C91}{\text{Example}}$: Matrix above has size 2 x 3.
- Its elements are called: entries, coefficients.
- $A_{i, j}$ refers to element at ith row and jth column in matrix $A$.
  - i is the row index and j is the column index.

$\color{#003660}{\text{In Python}}$, we use `numpy` and `np.array` to build matrices. The shape of the matrix can be accessed via the function `shape`.

In [7]:
import numpy as np

A = np.array([
    [0, 1, -2.3], 
    [1.3, 4, -0.1]
])
print(np.shape(A)); print(A.shape)
v = np.array([1, 2, 3, 4]); print(len(v))

(2, 3)
(2, 3)
4


$\color{#003660}{\text{In Python}}$, we can access the elements of the matrix.

In [18]:
v = [1.1, 2.2, 3.3, 4.3]; #print(len(v))

for v_index in range(len(v)):
    print(v[v_index])
    
for v_value in v:
    print(v_value)

1.1
2.2
3.3
4.3


In [29]:
print(A); print(A[0][2]); print(A[0, 2])
# Implement code that prints all entries of the matrix A
print("Begin for loop:")
print(A.shape)
n_rows = A.shape[0]; n_columns = A.shape[1]
n_rows, n_columns = A.shape

for i in range(n_rows):
    for j in range(n_columns):
        print(A[i, j])

[[ 0.   1.  -2.3]
 [ 1.3  4.  -0.1]]
-2.3
-2.3
Begin for loop:
(2, 3)
0.0
1.0
-2.3
1.3
4.0
-0.1


# Sizes/Shapes of Matrices

$\color{#EF5645}{\text{Definitions}}$: A m x n matrix $A$ is:
- tall if m > n,
- wide if m < n,
- square if m = n.

# Matrices, Vectors and Scalars

$\color{#EF5645}{\text{Definitions}}$:
- A 1 x 1 matrix is a number or scalar.
- A n x 1 matrix is an $n$-vector.
- A 1 x n matrix is a $n$-row-vector. 

Starting now, we will distinguish vectors and row vectors.

# Columns and rows of a matrix

$\color{#EF5645}{\text{Notations}}$: Take $A$ a $m \times n$ matrix with entries $A_{ij}$ for $i=1, ..., m$ and $j=1..., n$.
- Its jth column is the $m$-vector:
$$\begin{bmatrix}
A_{1j} \\
... \\
A_{mj}
\end{bmatrix}$$
- Its ith row is the $n$-row-vector: $[A_{i1}, ..., A_{in}]$.

# Slices of a matrix

$\color{#EF5645}{\text{Definition}}$ The slice of matrix $A_{p:q, r:s}$ is the matrix:
$$\begin{bmatrix}
A_{pr} & A_{p, r+1} & ... & A_{ps}  \\
... & ... & ... & ... \\
A_{qr} & A_{q, r+1} & ... & A_{qs}
\end{bmatrix}$$

$\color{#003660}{\text{In Python}}$, we can extract rows, columns and slices:

In [9]:
"""Extract rows, columns and slices from matrix A."""

'Extract rows, columns and slices from matrix A.'

# Block matrices

$\color{#EF5645}{\text{Definition}}$: A matrix $A$ composed from other matrices is called a block matrix:
$$A = \begin{bmatrix}
B & C  \\
D & E
\end{bmatrix}$$
where $B, C, D, E$ are called submatrices or blocks of $A$.

$\color{#047C91}{\text{Example}}$: Build a block-matrix.

# Column and row representation of matrix

$\color{#EF5645}{\text{Notations}}$: Take $A$ a $m \times n$ matrix with entries $A_{ij}$ for $i=1, ..., m$ and $j=1..., n$.
- $A$ is the block matrix of its columns $a_1, ..., a_n$:
  - $A = [a_1 ... a_n]$
- $A$ is the block matrix of its rows $b_1, ..., b_m$:
  - $A = \begin{bmatrix}
  b_1 \\
  \vdots \\
  b_m
  \end{bmatrix}.$

# Examples in ECE and beyond

- Images: $A_{ij}$ is intensity value at $i, j$.
- Weather: $A_{ij}$ is rainfall data at location $i$ on day $j$.
- Finances: $A_{ij}$ is the return of asset $i$ in period $j$

$\color{#047C91}{\text{Exercise}}$: In each of these, what do the rows and columns mean?

# Special Matrices

$\color{#EF5645}{\text{Definition}}$: The $m \times n$ zero matrix (resp. ones-matrix) is the matrix with all entries equal to $0$ (resp. to $!$).

$\color{#EF5645}{\text{Definition}}$: The identity matrix $I$ is the square matrix with $I_{ii} = 1$ and $I_{ij} = 0$ if $i\neq j$, for example:
$$\begin{bmatrix}
1 & 0 \\
0 & 1 
\end{bmatrix}.$$

$\color{#003660}{\text{In Python}}$:

In [11]:
"""Code zeroes matrices, ones matrices and the identity matrix"""

'Code zeroes matrices, ones matrices and the identity matrix'

# Diagonal Matrices

$\color{#EF5645}{\text{Definition}}$: A diagonal matrix $A$ is a square matrix with $A_{ij} = 0$ for $i \neq j$.
- diag$(a_1, ..., a_n)$ denotes the diagonal matrix with $A_{ii} = a_i$, for example:
$$\text{diag}(0.2, -3, 1.2) = \begin{bmatrix}
0.2 & 0 & 0 \\
0 & -3 & 0 \\
0 & 0 & 1.2
\end{bmatrix}$$

$\color{#003660}{\text{In Python}}$:

In [12]:
np.diag([0.2, -3, 1.2])

array([[ 0.2,  0. ,  0. ],
       [ 0. , -3. ,  0. ],
       [ 0. ,  0. ,  1.2]])

# Triangular Matrices

$\color{#EF5645}{\text{Definition}}$: A lower triangular matrix $A$ is a matrix such that $A_{ij} = 0$ for $i < j$. An upper triangular matrix $A$ is a matrix such that $A_{ij} = 0$ for $i > j$.

$\color{#047C91}{\text{Example}}$:
$\begin{bmatrix}
0.2 & 1.2 & 10 \\
0 & -3 & 0 \\
0 & 0 & 1.2
\end{bmatrix}$ (upper-triangular)

# Transpose

$\color{#EF5645}{\text{Definition}}$: The transpose of an $m \times n$ matrix $A$ is written $A^T$ and is defined by:
$$ (A^T)_{ij} = A_{ji}, \quad i = 1,..., n \quad j=1,...,m$$

$\color{#047C91}{\text{Example}}$: $\begin{bmatrix}
0.2 & 1.2 & 10 \\
0 & -3 & 0
\end{bmatrix}^T = \begin{bmatrix}
0.2 & 0 \\
1.2 & -3 \\
10 & 0
\end{bmatrix}$

$\color{#003660}{\text{In Python}}$:

In [10]:
"""Transpose a vector or a matrix."""

'Transpose a vector or a matrix.'

# Addition, Substraction and Scalar Multiplication

Just like vectors:
- we can add or subtract matrices of the same size
- we can multiply a matrix by a scalar.

$\color{#6D7D33}{\text{Property}}$: The transpose verifies:
- $(A^T)^T = A$.
- $(A + B)^T = A^T + B^T$.

# Matrix norm

$\color{#EF5645}{\text{Definition}}$: For a $m \times n$ matrix $A$, we define the matrix norm as:
$$||A|| = \sqrt{\sum_{i=1}^m \sum_{j=1}^n A_{ij}^2}.$$

$\color{#EF5645}{\text{Remark}}$: This definition agrees with the definition of norm of vectors when $n=1$ or $m=1$.


# Distance between two matrices

$\color{#EF5645}{\text{Definition}}$: The distance between two matrices $A$ and $B$ is defined as:
$$dist(A, B) = ||A - B||.$$

# Outline: 06 Matrices

- [Matrices](#sec-matrices)
- **[Matrix-vector multiplication](#matvec)**
- [Examples](#examples)