# ECE-3 Lab 5

## Matrix

$\color{#EF5645}{\text{Definition}}$: Rectangular array of numbers. For example, matrix A has 3 rows and 4 columns.

$A = \begin{bmatrix}1 & 4 & 5 & 7\\ 3 & -1 & 9 & 5\\ 4& 5 & 0 & 3\end{bmatrix}$

The code below describes how to define such a matrix

In [ ]:
import numpy as np

A = np.array([[1, 4, 5, 7],
              [3, -1, 9, 5],
              [4, 5, 0, 3]])
print(A)
print("Shape of A: ", A.shape)
print("No. of rows of A = ", A.shape[0])
print("No. of columns of A = ", A.shape[1])

[[ 1  4  5  7]
 [ 3 -1  9  5]
 [ 4  5  0  3]]
Shape of A:  (3, 4)
No. of rows of A =  3
No. of columns of A =  4


### Transpose of a matrix (exchange rows and columns) : `np.transpose()`


In [ ]:
# Note np.transpose() does not create a copy of an array
B = A.transpose().copy()
print(B)

# Changes in B does not affects A as we used np.copy()
B[0,0] = 500
print(A)
print(B)

[[ 1  3  4]
 [ 4 -1  5]
 [ 5  9  0]
 [ 7  5  3]]
[[ 1  4  5  7]
 [ 3 -1  9  5]
 [ 4  5  0  3]]
[[500   3   4]
 [  4  -1   5]
 [  5   9   0]
 [  7   5   3]]


### Changing the shape of a matrix : `np.reshape()`

In [ ]:
# Note np.copy() does not create a copy of an array
B = A.reshape(2,6).copy()
print(B)

# Changes in B does not affects A as we used np.copy()
B[0,0] = 500
print(A)
print(B)

[[ 1  4  5  7  3 -1]
 [ 9  5  4  5  0  3]]
[[ 1  4  5  7]
 [ 3 -1  9  5]
 [ 4  5  0  3]]
[[500   4   5   7   3  -1]
 [  9   5   4   5   0   3]]


### Some terminologies

Let $A$ be a $m$ x $n$ matrix ie $m$ rows and $n$ columns.
A is
- **tall** if $m>n$
- **wide** if $m<n$
- **square** if $m=n$


### Extracting rows and columns of a matrix

*Remember python uses `0`-based indexing*

$\color{#047C91}{\text{Example}}$:
- column `0` of A :  $\begin{bmatrix}1\\3\\4\end{bmatrix}\:\:\:\:$ code : `A[:,0]`

- row `2` of A : $\begin{bmatrix}4 & 5 & 0 & 3 \end{bmatrix}\:\:\:\:$ code : `A[2,:]` 

In [ ]:
#notice that the result is just an array so it is printed horizontally
print('Column 0 of A:')
print(A[:,0]) # column 0 of A.

print('Row 2 of A:')
print(A[2,:]) # row 2 of A

Column 0 of A:
[1 3 4]
Row 2 of A:
[4 5 0 3]


### Slices of a matrix

- `:` means extract all from that particular dimension
- `1:4` means extract at positions 1,2,3 (excluding 4)
- `-1` means extract the 1st position from the end


For example using the previous example of A:

$A = \begin{bmatrix}1 & 4 & 5 & 7\\ 3 & -1 & 9 & 5\\ 4& 5 & 0 & 3\end{bmatrix}$


- `A[1:3,:]` $\implies$ returns values at row index=1,2 and **all** column indices
- `A[0:1,:]`  $\implies$ returns values at row index=0 and **all** column indices
- `A[1, 1:2]` $\implies$ returns values at row index=1 and column index=1
- `A[1, -1]` $\implies$ returns values at row index=1 and column index=3 (last column)
- `A[1, -3:-1]` $\implies$ returns values at row index=1 and column index=1,2
- `A[:,:]` $\implies$ returns values at **all** row indices and **all** column indices ie entire A

In [ ]:
A[:, -3:-1]

array([[ 4,  5],
       [-1,  9],
       [ 5,  0]])

### Block matrices

$\color{#EF5645}{\text{Definition}}$: A matrix composed of other matrices is called a *block* matrix:
$A = \begin{bmatrix}B & C \\D & E\end{bmatrix}$

where $B,C,D,E$ are matrices.

In [ ]:
# defining B,C,D,E as 2x2 matrices

B = np.array([[4,5],
              [1,2]])

C = np.array([[-1,4],
              [0,8]])


D = np.array([[7,9],
              [5,0]])


E = np.array([[1,1],
              [7,7]])

A = np.array([[B, C],
              [D, E]])
print(A)

[[[[ 4  5]
   [ 1  2]]

  [[-1  4]
   [ 0  8]]]


 [[[ 7  9]
   [ 5  0]]

  [[ 1  1]
   [ 7  7]]]]


### Special matrices
 -  Diagonal matrix : A square matrix such that all off diagonal elements are equal to 0.

 $\color{#047C91}{\text{Example}}$: $\begin{bmatrix}5 & 0 & 0\\0 & 7 & 0\\ 0 & 0 & 0\end{bmatrix}\:\:$
 - Identity matrix : A square matrix such that all diagonal elements are equal to 1 and all other elements are 0.

$\color{#047C91}{\text{Example}}$: $I_4 = \begin{bmatrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\ 0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{bmatrix}\:\:$, $I_2 = \begin{bmatrix}1 & 0\\0 & 1\end{bmatrix}\:\: \implies$ `np.eye(2)` or `np.identity(2)`

- Zero matrix : $\begin{bmatrix}0 & 0\\0 & 0\end{bmatrix} \implies$ `np.zeros((2,2))`

- Ones matrix : $\begin{bmatrix}1 & 1\\1 & 1\end{bmatrix} \implies$ `np.ones((2,2))`

- Lower triangular matrix : A matrix such that $A_{ij}=0$ for $i<j$
- Upper triangular matrix : A matrix such that $A_{ij}=0$ for $i>j$ 


$\color{#047C91}{\text{Example}}$:

Classify the matrices below as upper triangular and/or lower triangular:

1. $A=\begin{bmatrix}1 & 7 & 0 & 9\\0 & 2 & 4 & 3\\ 0 & 0 & 7 & 10\\0 & 0 & 0 & 1\end{bmatrix}$

Answer: Upper triangular matrix

2. $B=\begin{bmatrix}1 & 0 & 0 & 0\\0 & 2 & 0 & 0\\ 0 & 0 & 7 & 0\\0 & 0 & 0 & 1\end{bmatrix}$

Answer: Diagonal matrix

3. $C=\begin{bmatrix}1 & 0 & 0 & 10\\0 & 2 & 0 & 0\\ 0 & 0 & 7 & 0\\0 & 0 & 0 & 1\end{bmatrix}$

Answer: Upper triangular matrix

*For the problems below, you can use the stated numpy functions but you must not explicitly set the matrix elements.*

$\color{#047C91}{\text{Exercise-1}}$:

Generate the following matrix using matrix slicing operations and the functions `np.zeros()` and `np.ones()`:


$\begin{bmatrix}
1 & 1 & 1 & 1 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 1 & 1 & 1 & 1\\\end{bmatrix}$

* Answer:
* A = np.ones((5,5))
* B = np.zeros((3,3))
* A[1:4,1:4] = B
* print(A)



$\color{#047C91}{\text{Exercise-2}}$:

Generate the following matrix using matrix slicing operations and the functions `np.zeros()`, `np.ones()`:


$\begin{bmatrix}
0 & 0 & 1 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\
1 & 1 & 1 & 1 & 1\\
0 & 0 & 1 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\\end{bmatrix}$

* Answer:
* A = np.zeros((5,5))
* B = np.ones((1,5))
* C = np.ones((5,1))
* A[2:3, :] = B
* A[:,2:3] = C
* print(A)


$\color{#047C91}{\text{Exercise-3}}$:

Generate the following matrix using matrix slicing operations and the functions `np.zeros()`, `np.ones()` and `np.fliplr()`:


$\begin{bmatrix}
1 & 0 & 0 & 0 & 1\\
0 & 1 & 0 & 1 & 0\\
0 & 0 & 2 & 0 & 0\\
0 & 1 & 0 & 1 & 0\\
1 & 0 & 0 & 0 & 1\\\end{bmatrix}$


Hint: Print `help(np.fliplr)` for more info !


* Answer:
* A = np.eye(5)
* A = A +np.fliplr(A)

* print(A)


### Matrix norm
$\color{#EF5645}{\text{Definition}}$: For a $m \times n$ matrix $A$, we define the matrix norm as:
$$||A|| = \sqrt{\sum_{i=1}^m \sum_{j=1}^n A_{ij}^2}.$$

$\color{#047C91}{\text{Example}}$: Compute the matrix norm of $A = \begin{bmatrix}
2 & 0 & 1\\
0 & 3 & 2 \end{bmatrix}.$

$||A|| = \sqrt{2^2 + 0^2 + 1^2 + 0^2 + 3^2 + 2^2} = \sqrt{18}$.

In [ ]:
# Matrix Norm
import numpy as np
A = np.array([[2,0,1],[0,3,2]])
print("A's norm is", np.linalg.norm(A))

A's norm is 4.242640687119285


### Distance between two matrices

$\color{#EF5645}{\text{Definition}}$: The distance between two matrices $A$ and $B$ is defined as:
$$dist(A, B) = ||A - B||.$$

$\color{#047C91}{\text{Example}}$: Compute the distance between $A = \begin{bmatrix}
2 & 0 & 1\\
0 & 3 & 2 \end{bmatrix}$ and $B = \begin{bmatrix}
1 & 0 & 1\\
0 & 2 & 2 \end{bmatrix}.$

$||A - B|| = ||\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \end{bmatrix}|| = \sqrt{2}$.

In [ ]:
# Distance between 2 matrices
import numpy as np
A = np.array([[2,0,1],[0,3,2]])
B = np.array([[1,0,1],[0,2,2]])
print("Distance between A and B is", np.linalg.norm(A - B))

Distance between A and B is 1.4142135623730951


### Matrix vector multiplication

Consider a matrix $A$ and a vector $b$. Let their product be equal to $y$.

$y = \begin{bmatrix}y_1\\y_2\\.\\.\\.\\y_n\end{bmatrix} = \begin{bmatrix}a_{11} & a_{12} & a_{13} & ... & a_{1n}\\ a_{21} & a_{22} & a_{23} & ... & a_{2n}\\. & . & . & ... & .\\. & . & . & ... & .\\. & . & . & ... & .\\a_{n1} & a_{n2} & a_{n3} & ... & a_{nn}\end{bmatrix}\:\:\begin{bmatrix}b_1 \\ b_2 \\ . \\ . \\ . \\ b_n\end{bmatrix}$


where,

$y_1 = a_{11}b_1 + a_{12}b_2 + ... a_{1n}b_n$

$y_2 = a_{21}b_1 + a_{22}b_2 + ... a_{2n}b_n$

.
.

$y_n = a_{n1}b_1 + a_{n2}b_2 + ... a_{nn}b_n$

In [ ]:
# Example

A = np.array([[1,2,3],  #shape (3,3)
              [2,0,5],
              [6,2,1]])
b = np.array([1,4,5]) #shape (3,)
print('y=' , A@b)


# or more specifically
b = np.array([[1], [4], [5]]) #shape (3,1)
print('With proper size formatting')
print('y=' , A@b)

y= [24 27 19]
With proper size formatting
y= [[24]
 [27]
 [19]]


In [ ]:
np.matmul(A,b)

array([[24],
       [27],
       [19]])