# ECE-3 Lab 2

## Contents
1. [Vectors](#Vectors)
2. [Linear Functions](#Linear-Functions)
3. [Norms](#Norms)
4. [Distance](#Distance)

## Vectors

- $\color{blue}{\text{Definition }}$ An ordered list of numbers, similar to arrays in Python.

- We say a **n-vector** has a total of *n* *elements/components*.
- $\color{blue}{\text{NOTE }}$ Indexes run from $0$ to $n-1$.
- Example :
$$A = \begin{bmatrix}
    -6.9 \\
    -5 \\
    1.2 \\
    -9.6
\end{bmatrix}\:\:\:
B = \begin{bmatrix}
    -6.9 ,-5, 1.2, -9.6
\end{bmatrix}$$


In [ ]:
import numpy as np

A = np.array([[-6.9],
                [-5],
                [1.2],
                [-9.6]])
print(A)
print(A.shape)

B = np.array([-6.9,-5,1.2,-9.6])
print(B)
print(B.shape)

[[-6.9]
 [-5. ]
 [ 1.2]
 [-9.6]]
(4, 1)
[-6.9 -5.   1.2 -9.6]
(4,)


$\color{blue}{\text{NOTE }}$

`C=A` where both `C`,`A` are both numpy arrays merely creates a reference to original array `A`. Changes made to A thereafter **DO** show up in `C` as well.

In [ ]:
C = A  # just creates a reference to A, DOES NOT creates a copy
print('Before making any change to A')
print(C)
A[2] = 0
print("After making a change to A")
print(C) #notice the changes propagate to A as well


Before making any change to A
[[-6.9]
 [-5. ]
 [ 1.2]
 [-9.6]]
After making a change to A
[[-6.9]
 [-5. ]
 [ 0. ]
 [-9.6]]


$\color{#EF5645}{\text{Matrices}}$

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("The dimension of the array is: ", A.ndim, '\n')
print("The total number of elements in the array are: ", A.size, '\n')
print("The shape of the array is: ", A.shape)

The dimension of the array is:  2 

The total number of elements in the array are:  6 

The shape of the array is:  (2, 3)


$\color{#EF5645}{\text{Block/Stacked Matrices}}$
$$P = \begin{bmatrix}
    1, 2, 3, 4
\end{bmatrix}$$
$$Q = \begin{bmatrix}
    5, 6, 7, 8
\end{bmatrix}$$

$$C = \begin{bmatrix}
    1, 2, 3, 4\\
    5, 6, 7, 8
\end{bmatrix}$$

$$D = \begin{bmatrix}
    1, 2, 3, 4, 5, 6, 7, 8
\end{bmatrix}$$



$\verb|Code|$
```python
P = np.array([1,2,3,4])
Q = np.array([5,6,7,8])
C = np.concatenate([[P],[Q]]) #vertical
D = np.concatenate([P,Q])     #horizontal
```

$\color{#EF5645}{\text{Ones Vector}}$
$$A = \begin{bmatrix}
    1\: 1\: 1\\
    1\: 1\: 1\\
\end{bmatrix}$$

```python
A = np.ones((2,3))          
```

$\color{#EF5645}{\text{Zero Vector}}$
$$B = \begin{bmatrix}
    0\: 0\: 0\: 0\\
    0\: 0\: 0\: 0\\
    0\: 0\: 0\: 0\\
\end{bmatrix}$$

```python
B = np.zeros((3,4))          
```


In [ ]:
# Code demonstrating ones and zeros vectors
E = np.ones((3,4))
F = np.zeros((3,4))
P = np.array([1,2,3,4])
Q = np.array([5,6,7,8])
C = np.concatenate([[P],[Q]])
D = np.concatenate([P,Q])
print(E)
print(F)
print(C)
print(D)

$\color{#EF5645}{\text{Some Basic Numpy Functions}}$

In [ ]:
a = np.array([3, 2, 1, 4])

print("The sum of the elements in a is: ", np.sum(a), '\n')
print("The minimum of a is: ", np.min(a), '\n')
print("If we sort a we get: ", np.sort(a), '\n')
print("We can also change the shape of a: ", np.reshape(a, (2, 2)), '\n')

b = np.array([5, 8, 7, 6])

print("We can merge it with another array like this: ", np.hstack((a, b)), '\n')
print("Or like this: ", np.vstack((a, b)))

The sum of the elements in a is:  10 

The minimum of a is:  1 

If we sort a we get:  [1 2 3 4] 

We can also change the shape of a:  [[3 2]
 [1 4]] 

We can merge it with another array like this:  [3 2 1 4 5 8 7 6] 

Or like this:  [[3 2 1 4]
 [5 8 7 6]]


$\color{#EF5645}{\text{Inner Product}}$

$\color{blue}{\text{Definition }}$ Inner product (or dot product) of two n-vectors $a$ and $b$ is defined as :
$$a^T b = a_1 b_1 + a_2 b_2 + a_3 b_3 + ... + a_n b_n$$

- Denoted by : $〈a, b〉, 〈a|b〉, (a, b), a · b$.

$\color{blue}{\text{Properties}}$
- $a^T b = b^T a$. (Prove this in class!)
- $(γa)^T b = γ(a^T b)$
- $(a + b)^T c = a^T c + b^T c$

$\verb|Code|$
```python
a = np.array([1,2,3])
b = np.array([8,2,4])
c = np.inner(a,b)
```

In [ ]:
# Code demonstrating inner product of two arrays
import numpy as np
a = np.array([1,2,3])
b = np.array([8,2,4])
# 3 different ways to compute inner product
c = np.inner(a,b)
d = a.T @ b
e = np.sum(a * b)
print(c)
print(d)
print(e)

24
24
24


$\color{blue}{\text{Exercise - 1}}$

A typical course utilizes several different weights for marks scored by a student across various tests such as quizzes, midterm and final over a quarter. Use the weight matrix W and marks obtained M to find the effective/total score obtained by a student.

**Weight Matrix W**

| Q   | M   | F   |
|-----|-----|-----|
| 20 % | 30 % | 50 %|


**Marks Obtained M**

| Q  | M  | F  |
|----|----|----|
| 15 | 45 | 70 |

*Hint: Use inner product*



In [4]:
# Exercise - 1
# Add your code below
W = np.array([0.2, 0.3, 0.5])
M = np.array([15, 45, 70])
a= np.inner(W,M)
b= W.T @M
print(a)
print(b)


51.5
51.5


[Go back to contents](#Contents)

## Linear Functions

$\color{#EF5645}{\text{Definition }}$
We say that $f$ satistifies the superposition property if:

$$f(\alpha x + \beta y) = \alpha f(x) + \beta f(y)$$

holds for all scalars $\alpha, \beta$ and all $n$-vectors $x, y$.

Satifies superposition property $\implies$ Linear

**Example:** All innner product functions are linear functions. (Prove this)

## Affine Functions

$\color{#EF5645}{\text{Definition }}$
A function that is linear plus a constant is called affine. Its general form is:

$$f(x) = a^Tx+b \quad \text{with $a$ an $n$-vector and $b$ a scalar}$$


## Gradient of a function


$$\nabla f(x) = \left(\frac{\partial f}{\partial x_1}(x), ..., \frac{\partial f}{\partial x_n}(x)\right).$$

where $\frac{\partial}{\partial x_i}$ is the partial derivative of $f$ with respect to the component $i$ of $x$.

[Go back to contents](#Contents)

## Norms. (Half way point/break)

$\color{#EF5645}{\text{Euclidean Norm}}$

Let $x$ be a n-dimensional vector i.e $$x = [x_1, x_2, ... x_n]$$

Then the Euclidean norm or $\ell_2$ norm (or just norm here) is given by:

$$||x||_2 = ||x|| = \sqrt{x_1^2 + x_2^2 + ... + x_n^2} = \sqrt{x^T x}$$

*Think about what would be $||x||_n$ in general*

In [ ]:
# Practice using numpy.linalg below

import numpy as np
x = np.array([1,2,7,-4])

# All three methods have the same result, verify !
print(np.linalg.norm(x))
print(np.sqrt(np.inner(x,x)))
print(np.sqrt(sum(x **2)))

8.366600265340756
8.366600265340756
8.366600265340756


$\color{#EF5645}{\text{Mean Square Value}}$

$$ \frac{x_1^2+ x_2^2+ ... + x_n^2}{n} = \frac{||x||^2}{n}$$

$\color{#EF5645}{\text{Root Mean Square (RMS) Value}}$

$$rms(x) = \sqrt{\frac{x_1^2+ x_2^2+ ... + x_n^2}{n}}=\frac{||x||}{\sqrt{n}}$$


$\color{blue}{\text{Exercise - 2}}$

In [2]:
# Exercise - 2 - write a function for L-P norm
# DO NOT CHANGE SECTION 1 and SECTION 3
# Add your code to SECTION 2


# Section-1 (DON'T CHANGE)
import numpy as np
arr = np.array([4,5,2,7])


# Section-2
def l_p_norm(arr,p):
    '''arr contains the array of numbers i.e vector
    Write a function to find l-p norm of vector arr'''
    # insert your code below
    x=np.absolute(arr)
    return np.power(np.sum(x**p),(1/p))


# Section-3 (DON'T CHANGE)
try:
    if(int(l_p_norm(arr,4))==7):
        print("Correct !")
    else:
        print("Something is wrong, please try again !")
    #break
except TypeError:
    print("Complete implementing the function and try again")

Correct !


$\color{#EF5645}{\text{Norm of block vectors}}$

Assume $d =[a, b, c]$ where $a,b,c$ are n-dimensional vectors. Then,
$$||d||^2=a^T a + b^T b + c^T c = ||a||^2 + ||b||^2 + ||c||^2$$

In other words:

*Norm-squared value of stacked vector is equal to the sum of norm-squared values of individual vectors.*

$\color{blue}{\text{Exercise - 3}}$
> **Hint:** You can reuse `l_p_norm(arr,p)` from the previous cell

In [3]:
# Exercise 3 - Write a function to find l-2 norm of a block vector
# DO NOT CHANGE SECTION 1 and SECTION 3
# Add your code to SECTION 2


# Section-1 (DON'T CHANGE)
import numpy as np
vecA = np.array([5,4,1])
vecB = np.array([6,6,8])
vecC = np.array([1,2,9])

# stacking vecA, vecB, vecC side-by-side
mat = np.stack((vecA,vecB,vecC),axis=1)
print(mat)


# Section-2
def block_norm(mat):
    """This function finds the l-2 norm of block vectors"""
    # insert your code below
    s = 0;
    for i in range(mat.shape[1]):
        col = mat[:,i]
        s += (l_p_norm(col,2)**2)
    return np.sqrt(s)

# Section-3 (DON'T CHANGE)
try:
    if(int(block_norm(mat))==16):
        print("Correct !")
    else:
        print("Something is wrong, please try again !")
    #break
except TypeError:
    print("Complete implementing the function and try again")

[[5 6 1]
 [4 6 2]
 [1 8 9]]
Correct !


[Go back to contents](#Contents)

## Distance

The distance between two 2-dimensional points $(x_1,y_1), (x_2,y_2)$ is given by:
$$d = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$$

The code to do this is shown below:

In [ ]:
# This code finds the distance between two points (x1,y1) and (x2,y2)
# Note that this is only for 2-dimensional points
import numpy as np

p1 = np.array([1,2])
p2 = np.array([3,7])
def dist_2d(p1,p2):
    distance_squared = (p2[0]-p1[0])**2 + (p2[1]-p1[1])**2
    return (np.sqrt(distance_squared))


print("Distance between", p1,"and", p2,"is:", dist_2d(p1,p2))
    

In general, the distance between two $n$-dimensional points $A \:(a_1,a_2,...,a_n)$ and $B\:(b_1,b_2,...,b_n)$ is given by:
$$d = ||A-B||_2 = \sqrt{(b_1-a_1)^2 + (b_2-a_2)^2 + ... + (b_n-a_n)^2}$$

Now build on the previous code to find the distance between two $n$-dimensional points.

$\color{blue}{\text{Exercise - 4}}$

In [5]:
# Exercise-4 : Implement a function to find the distance between two n-dimensional points
# DO NOT CHANGE SECTION 2
# Add your code to SECTION 1

# Section-1 
import numpy as np

def dist_nd(p1, p2):
    """This function finds the distance between two n-dimensional vectors"""
    #insert your code below
    ss = 0
    for i in range(len(p1)):
      ss += (p1[i] - p2[i])**2
    return ss**(1/2)

    
    
# Section-2 (DON'T CHANGE)
try:
    
    
    p1 = np.array([1,2])
    p2 = np.array([3,7])
    if(int(dist_nd(p1,p2))==5):
        print('Test case #1:')
        print("Result : Correct")
    else:
        print('Test case #1:')
        print("Result: Incorrect")
    print("You found distance between", p1,"and", p2,"is:", dist_nd(p1,p2))
    

    print('\n\nTest case #2:')
    p1 = np.array([1,2,9,-2])
    p2 = np.array([3,7,-4,-9])
    if(int(dist_nd(p1,p2))==15):
        print("Result : Correct")
    else:
        print("Result: Incorrect")
    print("You found distance between", p1,"and", p2,"is:", dist_nd(p1,p2))
    
except TypeError:
    print("Complete implementing the function and try again")    





Test case #1:
Result : Correct
You found distance between [1 2] and [3 7] is: 5.385164807134504


Test case #2:
Result : Correct
You found distance between [ 1  2  9 -2] and [ 3  7 -4 -9] is: 15.716233645501712


[Go back to contents](#Contents)