# ECE 3 - Lab 8

# Left Inverse
<font color='red'>**Definition**</font> 

A matrix $X$ that satisfies
$$XA = I$$
is called the *left inverse* of $A$. If such a matrix $X$ exists, we say $A$ is *left-invertible*.


<font color='red'>**Properties**</font>
- The left inverse of a matrix is **not** unique, except when $A$ is a 1x1 matrix i.e $A$ is a number.
- The dimensions of the left inverse of  $A_{mxn}$ is $X_{nxm}$ i.e same as $A^T$.


<font color='red'>**Existence**</font>
If a matrix $A$ has a left inverse **if and only if** columns of $A$ are linearly independent.


`Neccesary and sufficient condition`


<font color='blue'>**Corollary**</font>
If a matrix has more columns than rows (wide), it is not left-invertible.

Example:
$$\begin{bmatrix}
1 & 2 & 0 & 4 & 5\\
3 & 7 & 4 & 1 & 4\\
1 & 2 & 9 & 6 & 1\\
\end{bmatrix}$$






# Right Inverse
<font color='red'>Definition: </font> A matrix $X$ that satisfies
$$AX = I$$
is called the *right inverse* of $A$. If such a matrix $X$ exists, we say $A$ is *right-invertible*.

<font color='red'>**Properties**</font>
- The right inverse of a matrix is **not** unique, except when $A$ is a 1x1 matrix i.e $A$ is a number.
- The dimensions of the right inverse of  $A_{mxn}$ is $X_{nxm}$ i.e same as $A^T$.


<font color='red'>**Existence**</font>
If a matrix $A$ has a right inverse **if and only if** rows of $A$ are linearly independent.


`Neccesary and sufficient condition`


<font color='blue'>**Corollary**</font>
If a matrix has more rows than columns (tall), it is not right-invertible.

Example:
$$\begin{bmatrix}
1 & 2\\
3 & 9\\
1 & 2\\
8 & 4\\
\end{bmatrix}$$

$(A^{huhuhu})^{T}$

# Inverse of a matrix
<font color='red'>Definition: </font> A matrix $X$ that satisfies
$$AX = XA = I$$
is called the *inverse* of $A$. If such a matrix $X$ exists, we say $A$ is *invertible*.

<font color='red'>**Properties**</font>
- The inverse of a matrix is **unique**.
- It is simultaneously the left and right inverse of the given matrix.
- The dimensions of the inverse of $A_{mxn}$ is $X_{nxm}$ i.e same as $A^T$.


<font color='red'>**Existence**</font>
- If a matrix $A$ has an inverse **if and only if** both the left and right inverses exist i.e all the rows as well as columns of $A$ are linearly independent. 
- Clearly for $A$ to be invertible, $A$ cannot be tall or wide. Hence $A$ is a square matrix if at all it is invertible.

- **NOTE:** A square matrix need not to be always invertible. This is a *neccesary* but not a *sufficient* condition.

Example:
$$\begin{bmatrix}
0 & 0\\
0 & 1\\
\end{bmatrix}$$

# `np.linalg.solve(...)`

Consider the system of equations:
$$\begin{equation*}
x_1 + 2x_2 + x_3 = 8\\
x_1 + 2x_3 = 7\\
x_2 + 3x_3 = 11\\
\end{equation*}$$

Writing the above equation in terms of $Ax=b$
$$A = \begin{bmatrix}
1 & 2 & 1\\
1 & 0 & 2\\
0 & 1 & 3\\
\end{bmatrix}\:\:\:\:\: x = \begin{bmatrix}
x_1\\
x_2\\
x_3\\
\end{bmatrix}\:\:\:\:\: b = \begin{bmatrix}
8\\
7\\
11\\
\end{bmatrix}$$

`np.linalg.solve(A,b)` can be used to solve this system of equations:



In [ ]:
import numpy as np
A = np.array([[1,2,1],[1,0,2],[0,1,3]])
b = np.array([8,7,11])
x1 = np.linalg.solve(A,b)  # A is 3x3 and b is 3-vector
x2 = np.linalg.inv(A) @ b  # same result
print(x1)
print(x2)

[1. 2. 3.]
[1. 2. 3.]


# Exercise 1
Ronald invests $10,000, part at 3%, and the rest at 2.5%, both in interest bearing accounts.

The total yearly investment income (interest) is $283. How much did Ronald invest at each rate ?


In [ ]:
import numpy as np

A = np.array([[1,1],[0.03,0.025]])
b = np.array([10000,283])
x = np.linalg.solve(A,b)
print(x)

[6600. 3400.]


# Exercise 2

It is well known that if number of equations is equal to number of variables, the system of equations can be solved. Alex was given the following set of equations and was asked to obtain the solution vector i.e $[x_1,x_2,x_3]$. Find the solution to the given system of equations and report your findings.
$$\begin{equation*}
-x_1 + 3x_2 -2x_3 = 1\\
-x_1 + 4x_2 -3x_3 = 0\\
-x_1 + 5x_2 - 4x_3 = 0\\
\end{equation*}$$

In [ ]:
import numpy as np
A = np.array([[-1,3,-2],[-1,4,-3],[-1,5,-4]]);
b = np.array([1,0,0]).T
# A is not invertible [R2-R1 == 0.5*(R3-R1)]

# Exercise 3

<p align="center">
  <a>
    <img src="https://i.postimg.cc/XYXW9YPV/ex3.png"
         alt="ex3-image">
  </a>
</p>


Suppose that 100 insects are distributed in an enclosure consisting of
four chambers with passageways between them as shown above.

At the end of one minute, the insects have redistributed themselves.
Assume that:
- A minute is not enough time for an insect to visit more than
one chamber.
- At the end of a minute 40% of the insects in each
chamber have not left the chamber they occupied at the beginning of
the minute. 

The insects that leave a chamber disperse uniformly among
the chambers that are directly accessible from the one they initially
occupied—e.g., from #3, half move to #2 and half move to #4.

If at the end of one minute there are 12, 26, 25, and 37 insects
in chambers #1, #2, #3, and #4 respectively, determine what
the initial distribution had to be.



In [ ]:
#a_1 + a_2 + a_3 + a_4 =  100 (same as sum of below 4 equations)

#0.4a_1 + 0.2a_4  = 12
#0.4a_2 + 0.3a_3 + 0.2a_4 = 26
#0.4a_3 + 0.2a_4 + 0.3a_2 = 25
#0.4a_4 + 0.6a_1 + 0.3a_2 + 0.3a_3 = 37
import numpy as np
A = np.array([[0.4,0,0,0.2],[0,0.4,0.3,0.2],[0,0.3,0.4,0.2],[0.6,0.3,0.3,0.4]]);
b = np.array([12,26,25,37]).T
y = np.linalg.solve(A,b)
print(y)

y = np.linalg.inv(A) @ b
print(y)

[10. 30. 20. 40.]
[10. 30. 20. 40.]


## Exercise 4

The 4-vector $c$ gives the coefficients of a cubic polynomial,

$$p(x)=c_1 +c_2x+c_3x^2 +c_4x^3$$

We seek the coefficients that satisfy

$$p(−1.1) = 0.5 = b_1,~ p(−0.4) = 0.3 = b_2, ~p(0.2) =  -0.1 = b_3, ~ p(0.8) = 1.2 = b_4$$

Find a matrix $A$ such that you can express this as the system of 4 equations in 4 variables $Ac = b$. Then using the inverse of $A$ find $c$.

In [ ]:
# write your solution here:
# sol: [-0.06615256 -0.52970567  1.52295804  1.39692179]
import numpy as np

A = np.array([[1, -1.1, (-1.1)**2, (-1.1)**3],
              [1, -0.4, (-0.4)**2, (-0.4)**3],
              [1, 0.2, (0.2)**2, (0.2)**3],
              [1, 0.8, (0.8)**2, (0.8)**3]])

b = np.array([0.5, 0.3, -0.1, 1.2])

print(np.linalg.inv(A) @ b)

[-0.06615256 -0.52970567  1.52295804  1.39692179]


## Exercise 5

We consider the problem of balancing the chemical reaction:

$$a_1 Cr_2 O_7^{2−} + a_2Fe^{2+} + a_3H^+ → b_1 Cr^{3+} + b_2 Fe^{3+} + b_3 H_2O$$

where the superscript gives the charge of each reactant and product. There are 4 atoms (Cr, O, Fe, H) and charge to balance.

The reactant and product matrices are (using the order just listed):

$$R = \begin{bmatrix}
2 & 0 & 0\\
7 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
-2 & 2 & 1\\
\end{bmatrix},~
P = \begin{bmatrix}
1 & 0 & 0\\
0 & 0 & 1\\
0 & 1 & 0\\
0 & 0 & 2\\
3 & 3 & 0\\
\end{bmatrix}$$

For $a = [a_1~ a_2~ a_3]^T$ and $a = [b_1~ b_2~ b_3]^T$, it must be $Ra=Pb$. This can also be expressed as:

$$\begin{bmatrix} R &-P\end{bmatrix} \begin{bmatrix} a \\ b
\end{bmatrix} = 0$$

Furthermore, assume that $a_1 = 1$.

$$\begin{bmatrix} R &-P \\ e_1^T & 0\end{bmatrix} \begin{bmatrix} a \\ b 
\end{bmatrix} = e_6$$
Utilize the above formula and your knowledge about the matrix inverse to find $a$ and $b$. 

In [ ]:
# write your code below

import numpy as np

R = np.array([[2, 0, 0],
              [7, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
              [-2, 2, 1]])

P = np.array([[1, 0, 0],
              [0, 0, 1],
              [0, 1, 0],
              [0, 0, 2],
              [3, 3, 0]])

C = np.vstack((np.hstack((R, -P)), np.array([1, 0, 0, 0, 0, 0])))
d = np.array([0, 0, 0, 0, 0, 1])

print(np.linalg.inv(C) @ d)

[ 1.  6. 14.  2.  6.  7.]
